// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frjkylcanpxadtdumsgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyamt5bGNhbnB4YWR0ZHVtc2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzU5MTQsImV4cCI6MjA3MjU1MTkxNH0.upL-8cI3VvmwxN4VgDstwlfkNFFqxnDw2m6-uPd-dJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});